### ISSUE TITLE
What's up Bro!

### ISSUE THREAD

**Issue by wuyiqun0718** [marsinearth/decisionmaker#1]
How's going? Your app looks interesting!

**Comment by marsinearth** [comment]
haha, you used issue tracker as a messenger? nice and sorry, it's because I don't have any contact method...indeed, my US number is still alive since I'm using the free google voice/hangout! I finally went back to Korea and working here at a small start-up. I'll call ya sometime. I guess your number isn't changed...?

**Comment by wuyiqun0718** [comment]
haha, I'm actually here to point out you still used var once in your app and I recommend that stick to let and const. Also, you don't have to put constructor property in your class, you can do state = {} directly. Anyways, that's just minor things.

**Comment by wuyiqun0718** [comment]
Yeah, I didn't know you are still using that number, but I heard you went back so I tried to reach you through Allo. Sorry I've been very busy this year and I haven't contacted you for months until I heard you went back, I hope you were doing well. But I'm glad you got the chance to start coding again and yes I'm still using the same number.

**Comment by marsinearth** [comment]
Haha, actually I'm using let and const only these days, this project is actually done quite a long ago, had a permission issue due to my personal account(this one) and my company account of github and gh-pages default settings so that I had to re-init this repo. The current version changed some points with using react PureComponent and etc. I'm working at Korea now cuz couldn't resolved the visa issue. I'll go back to the US sometime later though, definitely. I'll contact you later with your 469 number!
